version: '3'
services:
  support-service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - FLASK_APP=supportService.py
      - DATABASE_URL=$DATABASE_URL
      - FLASK_ENV=development
      - LD_CLIENT_KEY=$LD_CLIENT_KEY
    command: bash run.sh
    depends_on:
      - db
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=supportService
      - POSTGRES_PASSWORD=supportService
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

