version: '3'
services:
  support-service:
    hostname: supportservice.dev
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=$DATABASE_URL
      - FLASK_ENV=development
      - LD_CLIENT_KEY=$LD_CLIENT_KEY
      - LD_FRONTEND_KEY=$LD_FRONTEND_KEY
    command: bash run.sh
    depends_on:
      - db
      - cache
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=supportService
      - POSTGRES_PASSWORD=supportService
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"

  apm:
    image: elastic/apm-server:6.4.2
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"